#### Makefile for IAV libraries ### 

############### MAKE ###############

all:
	$(MAKE) -C ./UtilityFunctions
	$(MAKE) -C ./PIDController
	
############### CLEAN ###############

.PHONY: clean

clean:

	$(MAKE) clean -C ./UtilityFunctions
	$(MAKE) clean -C ./PIDController

	