#### Makefile for IAV libraries ### 

############### MAKE ###############

all:
	$(MAKE) -C ./UtilityFunctions

	
############### CLEAN ###############

.PHONY: clean

clean:

	$(MAKE) clean -C ./UtilityFunctions

	