#### Makefile for IAV Sensor Manager Utilities ### 

############### MAKE ###############

all:
	$(MAKE) -C ./DisplayGPS
	$(MAKE) -C ./DisplayIMU
	$(MAKE) -C ./DisplayLidar
	
############### CLEAN ###############

.PHONY: clean

clean:

	$(MAKE) clean -C ./DisplayGPS
	$(MAKE) clean -C ./DisplayIMU
	$(MAKE) clean -C ./DisplayLidar
	